export { default as Navigation } from "./Navigation";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Crud } from "./Crud";
export { default as DataInputForm } from "./DataInputForm";
export { default as ShowData } from "./ShowData";
export { default as Sidebar } from "./Sidebar";
export { default as Footer } from "./Footer";
export { default as Error } from "./Error";
